class OrdersElement:
    # orders page elements
    phoneField = "//body/div[@id='root']/div[1]/div[2]/div[1]/span[1]/form[1]/div[1]/div[1]/span[1]/div[1]/input[1]"
    phone = "1950000000"
    clickSend = "//body/div[@id='root']/div[1]/div[2]/div[1]/span[1]/form[1]/input[1]"
    passwordField = "//body/div[@id='root']/div[1]/div[2]/div[1]/span[1]/form[1]/div[1]/div[1]/span[1]/div[1]/input[1]"
    password = "1234"
    clickLog = "//body/div[@id='root']/div[1]/div[2]/div[1]/span[1]/form[1]/input[1]"
    order_page_path = "//body[1]/div[1]/div[1]/div[2]/div[1]/nav[1]/div[2]/a[5]/span[2]"
    search = "//input[@placeholder='חיפוש בהזמנות']"
    table = "//tbody/tr[1]"
    order = "//tbody/tr[2]"
    error_msg = "//body/div[@id='root']/div[1]/div[2]/main[1]/div[2]/div[1]/div[2]/div[1]/div[2]/div[2]//body/div[@id='root']/div[1]/div[2]/main[1]/div[2]/div[1]/div[2]/div[1]/div[2]/div[2]"
    points_butten = "//body/div[@id='root']/div[1]/div[2]/main[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]"
    file_path = "C:/Users/Default/Downloads"
    ready_path = "//body[1]/div[1]/div[1]/div[2]/main[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/span[1]/i[1]"
    export = "//body/div[@id='root']/div[1]/div[2]/main[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]"